import Navbar from "@/app/Components/Navbar/navbar";

export const metadata = {
  title: "Dashboard Admin",
  description: "Generated by create next app",
};

export default function DashboardAdminLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#F8F8F8] min-h-screen">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
